import { Film } from './types';

export const DUMMY_DATA: Film[] = [
  // Movies (20)
  {
    id: 'm1',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Inception',
    turkishTitle: 'Başlangıç',
    releaseYear: '2010',
    category: 'Bilim Kurgu',
    plot: 'Hırsız Dom Cobb, insanların rüyalarına girerek sırlarını çalar. Ona imkansız bir görev verilir: Bir fikri çalmak yerine, bir zihne fikir yerleştirmek.',
    actors: 'Leonardo DiCaprio\nJoseph Gordon-Levitt\nElliot Page',
    imdbRating: '8.8/10',
    rating: 9,
    watchedDate: '2023-05-10',
    companions: ['Eşim'],
    notes: 'Harika bir kurgu, defalarca izlenebilir.',
    trailerLink: 'https://www.youtube.com/watch?v=YoHD9XEInc0'
  },
  {
    id: 'm2',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'The Dark Knight',
    turkishTitle: 'Kara Şövalye',
    releaseYear: '2008',
    category: 'Aksiyon',
    plot: 'Batman, Joker adındaki kaotik bir suç dehasıyla yüzleşirken Gotham Şehri\'ni kurtarmaya çalışır.',
    actors: 'Christian Bale\nHeath Ledger\nAaron Eckhart',
    imdbRating: '9.0/10',
    rating: 10,
    watchedDate: '2023-06-15',
    companions: ['Arkadaşlarım'],
    notes: 'Joker performansı efsane.',
    trailerLink: 'https://www.youtube.com/watch?v=EXeTwQWrcwY'
  },
  {
    id: 'm3',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Interstellar',
    turkishTitle: 'Yıldızlararası',
    releaseYear: '2014',
    category: 'Bilim Kurgu',
    plot: 'Bir grup astronot, insanlığın hayatta kalmasını sağlamak için bir solucan deliğinden geçerek yeni bir yuva arar.',
    actors: 'Matthew McConaughey\nAnne Hathaway\nJessica Chastain',
    imdbRating: '8.7/10',
    rating: 10,
    watchedDate: '2023-07-20',
    companions: ['Ailem'],
    notes: 'Müzikleri ve görselliği büyüleyici.',
    trailerLink: 'https://www.youtube.com/watch?v=zSWdZVtXT7E'
  },
  {
    id: 'm4',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Pulp Fiction',
    turkishTitle: 'Ucuz Roman',
    releaseYear: '1994',
    category: 'Dram',
    plot: 'İki tetikçi, bir boksör ve bir çift soyguncunun hayatları, şiddet ve kurtuluş dolu bir hikayede kesişir.',
    actors: 'John Travolta\nUma Thurman\nSamuel L. Jackson',
    imdbRating: '8.9/10',
    rating: 9,
    watchedDate: '2023-08-05',
    companions: ['Yalnız'],
    notes: 'Diyaloglar çok iyi.',
    trailerLink: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY'
  },
  {
    id: 'm5',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Fight Club',
    turkishTitle: 'Dövüş Kulübü',
    releaseYear: '1999',
    category: 'Dram',
    plot: 'Uykusuzluk çeken bir ofis çalışanı ve sabun satıcısı, yeraltı bir dövüş kulübü kurarak toplumsal normlara meydan okur.',
    actors: 'Brad Pitt\nEdward Norton\nHelena Bonham Carter',
    imdbRating: '8.8/10',
    rating: 9,
    watchedDate: '2023-09-12',
    companions: ['Arkadaşlarım'],
    notes: 'Sonu şaşırtıcı.',
    trailerLink: 'https://www.youtube.com/watch?v=qtRKdVHc-cE'
  },
  {
    id: 'm6',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'The Matrix',
    turkishTitle: 'Matrix',
    releaseYear: '1999',
    category: 'Bilim Kurgu',
    plot: 'Bir bilgisayar korsanı, yaşadığı dünyanın aslında makineler tarafından kontrol edilen bir simülasyon olduğunu keşfeder.',
    actors: 'Keanu Reeves\nLaurence Fishburne\nCarrie-Anne Moss',
    imdbRating: '8.7/10',
    rating: 10,
    watchedDate: '2023-10-01',
    companions: ['Eşim'],
    notes: 'Aksiyon sahneleri devrim niteliğinde.',
    trailerLink: 'https://www.youtube.com/watch?v=vKQi3bBA1y8'
  },
  {
    id: 'm7',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Forrest Gump',
    turkishTitle: 'Forrest Gump',
    releaseYear: '1994',
    category: 'Dram',
    plot: 'Düşük IQ\'lu bir adamın, 20. yüzyılın önemli tarihi olaylarına tanıklık ederken yaşadığı dokunaklı hayat hikayesi.',
    actors: 'Tom Hanks\nRobin Wright\nGary Sinise',
    imdbRating: '8.8/10',
    rating: 9,
    watchedDate: '2023-11-15',
    companions: ['Ailem'],
    notes: 'Çok duygusal bir film.',
    trailerLink: 'https://www.youtube.com/watch?v=bLvqoHBptjg'
  },
  {
    id: 'm8',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'The Godfather',
    turkishTitle: 'Baba',
    releaseYear: '1972',
    category: 'Dram',
    plot: 'Güçlü bir İtalyan-Amerikan suç ailesinin reisi, imparatorluğunu isteksiz oğluna devreder.',
    actors: 'Marlon Brando\nAl Pacino\nJames Caan',
    imdbRating: '9.2/10',
    rating: 10,
    watchedDate: '2023-12-01',
    companions: ['Yalnız'],
    notes: 'Sinema tarihinin en iyilerinden.',
    trailerLink: 'https://www.youtube.com/watch?v=sY1S34973zA'
  },
  {
    id: 'm9',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Parasite',
    turkishTitle: 'Parazit',
    releaseYear: '2019',
    category: 'Dram',
    plot: 'Fakir bir aile, zengin bir ailenin hayatına sızarak beklenmedik olayların fitilini ateşler.',
    actors: 'Song Kang-ho\nLee Sun-kyun\nCho Yeo-jeong',
    imdbRating: '8.5/10',
    rating: 9,
    watchedDate: '2024-01-10',
    companions: ['Eşim'],
    notes: 'Sınıf ayrımını çok iyi anlatıyor.',
    trailerLink: 'https://www.youtube.com/watch?v=5xH0HfJHsaY'
  },
  {
    id: 'm10',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Spirited Away',
    turkishTitle: 'Ruhların Kaçışı',
    releaseYear: '2001',
    category: 'Animasyon',
    plot: 'Küçük bir kız, ailesini kurtarmak için ruhların ve tanrıların dünyasında çalışmak zorunda kalır.',
    actors: 'Rumi Hiiragi\nMiyu Irino\nMari Natsuki',
    imdbRating: '8.6/10',
    rating: 9,
    watchedDate: '2024-02-05',
    companions: ['Ailem'],
    notes: 'Miyazaki şaheseri.',
    trailerLink: 'https://www.youtube.com/watch?v=ByXuk9QqQmc'
  },
  {
    id: 'm11',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Upcoming',
    originalTitle: 'Dune: Part Two',
    turkishTitle: 'Dune: Çöl Gezegeni Bölüm İki',
    releaseYear: '2024',
    category: 'Bilim Kurgu',
    plot: 'Paul Atreides, ailesini yok eden komploculara karşı intikam yolculuğuna devam ederken evrenin kaderini belirler.',
    actors: 'Timothée Chalamet\nZendaya\nRebecca Ferguson',
    imdbRating: '8.9/10',
    rating: 0,
    releaseDate: '2024-03-01',
    companions: [],
    notes: 'Sinemada izlenmeli.',
    trailerLink: 'https://www.youtube.com/watch?v=Way9Dexny3w'
  },
  {
    id: 'm12',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Gladiator',
    turkishTitle: 'Gladyatör',
    releaseYear: '2000',
    category: 'Aksiyon',
    plot: 'Eski bir Romalı general, ailesini katleden ve kendisini köleliğe mahkum eden imparatordan intikam almak için gladyatör olur.',
    actors: 'Russell Crowe\nJoaquin Phoenix\nConnie Nielsen',
    imdbRating: '8.5/10',
    rating: 9,
    watchedDate: '2024-03-15',
    companions: ['Arkadaşlarım'],
    notes: 'Destansı bir hikaye.',
    trailerLink: 'https://www.youtube.com/watch?v=owK1qxDselE'
  },
  {
    id: 'm13',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Joker',
    turkishTitle: 'Joker',
    releaseYear: '2019',
    category: 'Dram',
    plot: 'Toplum tarafından dışlanan bir komedyen, Gotham Şehri\'nde kaosun ve şiddetin simgesi haline gelir.',
    actors: 'Joaquin Phoenix\nRobert De Niro\nZazie Beetz',
    imdbRating: '8.4/10',
    rating: 9,
    watchedDate: '2024-04-01',
    companions: ['Eşim'],
    notes: 'Oyunculuk muazzam.',
    trailerLink: 'https://www.youtube.com/watch?v=zAGVQLHvwOY'
  },
  {
    id: 'm14',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Avengers: Endgame',
    turkishTitle: 'Yenilmezler: Son Oyun',
    releaseYear: '2019',
    category: 'Aksiyon',
    plot: 'Yenilmezler, Thanos\'un evrene verdiği zararı geri almak için son bir kez bir araya gelir.',
    actors: 'Robert Downey Jr.\nChris Evans\nMark Ruffalo',
    imdbRating: '8.4/10',
    rating: 8,
    watchedDate: '2024-04-20',
    companions: ['Arkadaşlarım'],
    notes: 'Bir devrin sonu.',
    trailerLink: 'https://www.youtube.com/watch?v=TcMBFSGVi1c'
  },
  {
    id: 'm15',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'The Lion King',
    turkishTitle: 'Aslan Kral',
    releaseYear: '1994',
    category: 'Animasyon',
    plot: 'Genç bir aslan prens, babasının ölümünün ardından krallığını geri almak için geri döner.',
    actors: 'Matthew Broderick\nJeremy Irons\nJames Earl Jones',
    imdbRating: '8.5/10',
    rating: 10,
    watchedDate: '2024-05-05',
    companions: ['Ailem'],
    notes: 'Çocukluğumun en sevdiğim filmi.',
    trailerLink: 'https://www.youtube.com/watch?v=lFzVjeohZg4'
  },
  {
    id: 'm16',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Titanic',
    turkishTitle: 'Titanik',
    releaseYear: '1997',
    category: 'Dram',
    plot: 'Batmaz denilen gemide farklı sınıflardan iki gencin yaşadığı trajik aşk hikayesi.',
    actors: 'Leonardo DiCaprio\nKate Winslet\nBilly Zane',
    imdbRating: '7.9/10',
    rating: 8,
    watchedDate: '2024-05-20',
    companions: ['Eşim'],
    notes: 'Görsel efektleri hala çok iyi.',
    trailerLink: 'https://www.youtube.com/watch?v=CHekzSiZjrY'
  },
  {
    id: 'm17',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Avatar',
    turkishTitle: 'Avatar',
    releaseYear: '2009',
    category: 'Bilim Kurgu',
    plot: 'Felçli bir asker, Pandora gezegenindeki yerli halkın arasına sızmak için bir avatar kullanır.',
    actors: 'Sam Worthington\nZoe Saldana\nSigourney Weaver',
    imdbRating: '7.9/10',
    rating: 8,
    watchedDate: '2024-06-10',
    companions: ['Arkadaşlarım'],
    notes: '3D deneyimi harikaydı.',
    trailerLink: 'https://www.youtube.com/watch?v=5PSNL1qE6VY'
  },
  {
    id: 'm18',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Oppenheimer',
    turkishTitle: 'Oppenheimer',
    releaseYear: '2023',
    category: 'Dram',
    plot: 'Atom bombasının babası olarak bilinen J. Robert Oppenheimer\'ın hayatı ve Manhattan Projesi.',
    actors: 'Cillian Murphy\nEmily Blunt\nMatt Damon',
    imdbRating: '8.4/10',
    rating: 9,
    watchedDate: '2024-07-01',
    companions: ['Eşim'],
    notes: 'Ses tasarımı ve oyunculuklar harika.',
    trailerLink: 'https://www.youtube.com/watch?v=uYPbbksJxIg'
  },
  {
    id: 'm19',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Barbie',
    turkishTitle: 'Barbie',
    releaseYear: '2023',
    category: 'Komedi',
    plot: 'Barbie, mükemmel dünyasından ayrılarak gerçek dünyada kendini keşfetme yolculuğuna çıkar.',
    actors: 'Margot Robbie\nRyan Gosling\nAmerica Ferrera',
    imdbRating: '6.9/10',
    rating: 7,
    watchedDate: '2024-07-15',
    companions: ['Eşim'],
    notes: 'Eğlenceli ve düşündürücü.',
    trailerLink: 'https://www.youtube.com/watch?v=pBk4NYhWNMM'
  },
  {
    id: 'm20',
    createdAt: new Date().toISOString(),
    type: 'Movie',
    status: 'Watched',
    originalTitle: 'Spider-Man: Into the Spider-Verse',
    turkishTitle: 'Örümcek-Adam: Örümcek Evreninde',
    releaseYear: '2018',
    category: 'Animasyon',
    plot: 'Miles Morales, farklı evrenlerden gelen diğer Örümcek-Adamlarla birleşerek dünyayı kurtarmaya çalışır.',
    actors: 'Shameik Moore\nJake Johnson\nHailee Steinfeld',
    imdbRating: '8.4/10',
    rating: 10,
    watchedDate: '2024-08-01',
    companions: ['Arkadaşlarım'],
    notes: 'Animasyon tarzı muazzam.',
    trailerLink: 'https://www.youtube.com/watch?v=g4HbzUKp6A4'
  },

  // Series (20)
  {
    id: 's1',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Breaking Bad',
    turkishTitle: 'Breaking Bad',
    releaseYear: '2008',
    category: 'Dram',
    plot: 'Kanser teşhisi konan bir kimya öğretmeni, ailesinin geleceğini garanti altına almak için eski bir öğrencisiyle uyuşturucu üretmeye başlar.',
    actors: 'Bryan Cranston\nAaron Paul\nAnna Gunn',
    imdbRating: '9.5/10',
    rating: 10,
    watchedDate: '2023-01-15',
    companions: ['Eşim'],
    notes: 'Gelmiş geçmiş en iyi dizi.',
    seasons: 5,
    totalEpisodes: 62,
    trailerLink: 'https://www.youtube.com/watch?v=HhesaQXLuRY'
  },
  {
    id: 's2',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Game of Thrones',
    turkishTitle: 'Taht Oyunları',
    releaseYear: '2011',
    category: 'Dram',
    plot: 'Yedi Krallık\'ın kontrolü için soylu aileler arasında süregelen güç savaşları ve kuzeyden gelen kadim bir tehdit.',
    actors: 'Emilia Clarke\nKit Harington\nPeter Dinklage',
    imdbRating: '9.2/10',
    rating: 9,
    watchedDate: '2023-02-20',
    companions: ['Eşim'],
    notes: 'Son sezonu hariç mükemmel.',
    seasons: 8,
    totalEpisodes: 73,
    trailerLink: 'https://www.youtube.com/watch?v=gcTkNV5Vg1E'
  },
  {
    id: 's3',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Stranger Things',
    turkishTitle: 'Stranger Things',
    releaseYear: '2016',
    category: 'Bilim Kurgu',
    plot: 'Küçük bir kasabada bir çocuğun kaybolmasıyla ortaya çıkan doğaüstü olaylar ve gizli hükümet deneyleri.',
    actors: 'Millie Bobby Brown\nFinn Wolfhard\nWinona Ryder',
    imdbRating: '8.7/10',
    rating: 9,
    watchedDate: '2023-03-10',
    companions: ['Ailem'],
    notes: '80\'ler atmosferi harika.',
    seasons: 4,
    totalEpisodes: 34,
    trailerLink: 'https://www.youtube.com/watch?v=b9EkMc79ZSU'
  },
  {
    id: 's4',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Friends',
    turkishTitle: 'Friends',
    releaseYear: '1994',
    category: 'Komedi',
    plot: 'Manhattan\'da yaşayan altı arkadaşın komik ve duygusal hayat hikayeleri.',
    actors: 'Jennifer Aniston\nCourteney Cox\nMatthew Perry',
    imdbRating: '8.9/10',
    rating: 10,
    watchedDate: '2023-04-01',
    companions: ['Eşim'],
    notes: 'Her zaman izlenebilir, kafa dağıtmak için birebir.',
    seasons: 10,
    totalEpisodes: 236,
    trailerLink: 'https://www.youtube.com/watch?v=hDNNmeeJs1Q'
  },
  {
    id: 's5',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'The Office',
    turkishTitle: 'The Office',
    releaseYear: '2005',
    category: 'Komedi',
    plot: 'Bir kağıt şirketinin şubesindeki çalışanların günlük ofis hayatlarını anlatan sahte belgesel tarzı komedi.',
    actors: 'Steve Carell\nRainn Wilson\nJohn Krasinski',
    imdbRating: '9.0/10',
    rating: 10,
    watchedDate: '2023-05-15',
    companions: ['Yalnız'],
    notes: 'Michael Scott karakteri efsane.',
    seasons: 9,
    totalEpisodes: 201,
    trailerLink: 'https://www.youtube.com/watch?v=LHOtME2DL4g'
  },
  {
    id: 's6',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Sherlock',
    turkishTitle: 'Sherlock',
    releaseYear: '2010',
    category: 'Dram',
    plot: 'Ünlü dedektif Sherlock Holmes ve ortağı Dr. Watson\'ın günümüz Londra\'sındaki maceraları.',
    actors: 'Benedict Cumberbatch\nMartin Freeman\nAndrew Scott',
    imdbRating: '9.1/10',
    rating: 9,
    watchedDate: '2023-06-01',
    companions: ['Eşim'],
    notes: 'Zekice kurgulanmış bölümler.',
    seasons: 4,
    totalEpisodes: 13,
    trailerLink: 'https://www.youtube.com/watch?v=xK7S9mrFWL4'
  },
  {
    id: 's7',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Black Mirror',
    turkishTitle: 'Black Mirror',
    releaseYear: '2011',
    category: 'Bilim Kurgu',
    plot: 'Teknolojinin insan hayatı üzerindeki karanlık ve beklenmedik etkilerini anlatan antoloji dizisi.',
    actors: 'Daniel Lapaine\nHannah John-Kamen\nMichaela Coel',
    imdbRating: '8.7/10',
    rating: 9,
    watchedDate: '2023-07-10',
    companions: ['Yalnız'],
    notes: 'Bazı bölümler çok sarsıcı.',
    seasons: 6,
    totalEpisodes: 27,
    trailerLink: 'https://www.youtube.com/watch?v=V0HC7n7vH2U'
  },
  {
    id: 's8',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'The Crown',
    turkishTitle: 'The Crown',
    releaseYear: '2016',
    category: 'Dram',
    plot: 'Kraliçe II. Elizabeth\'in saltanatı ve İngiliz kraliyet ailesinin yaşadığı siyasi ve kişisel olaylar.',
    actors: 'Claire Foy\nOlivia Colman\nImelda Staunton',
    imdbRating: '8.6/10',
    rating: 8,
    watchedDate: '2023-08-20',
    companions: ['Eşim'],
    notes: 'Prodüksiyon kalitesi çok yüksek.',
    seasons: 6,
    totalEpisodes: 60,
    trailerLink: 'https://www.youtube.com/watch?v=JWtnJjn6ng0'
  },
  {
    id: 's9',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Succession',
    turkishTitle: 'Succession',
    releaseYear: '2018',
    category: 'Dram',
    plot: 'Dünyanın en büyük medya şirketlerinden birini yöneten ailenin, babalarının emekliliği sonrası yaşadığı güç savaşları.',
    actors: 'Brian Cox\nJeremy Strong\nSarah Snook',
    imdbRating: '8.9/10',
    rating: 10,
    watchedDate: '2023-09-30',
    companions: ['Eşim'],
    notes: 'Karakter gelişimleri ve diyaloglar muazzam.',
    seasons: 4,
    totalEpisodes: 39,
    trailerLink: 'https://www.youtube.com/watch?v=OzYxJV_V3u8'
  },
  {
    id: 's10',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'The Bear',
    turkishTitle: 'The Bear',
    releaseYear: '2022',
    category: 'Dram',
    plot: 'Genç ve yetenekli bir şef, ailesinden kalan sandviç dükkanını yönetmek için Chicago\'ya döner.',
    actors: 'Jeremy Allen White\nEbon Moss-Bachrach\nAyo Edebiri',
    imdbRating: '8.6/10',
    rating: 9,
    watchedDate: '2023-11-05',
    companions: ['Yalnız'],
    notes: 'Mutfaktaki kaos çok iyi yansıtılmış.',
    seasons: 2,
    totalEpisodes: 18,
    trailerLink: 'https://www.youtube.com/watch?v=y-c9Z7njC8Y'
  },
  {
    id: 's11',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'The Last of Us',
    turkishTitle: 'The Last of Us',
    releaseYear: '2023',
    category: 'Dram',
    plot: 'Modern uygarlığın yok olmasının ardından hayatta kalan Joel, genç Ellie\'yi karantina bölgesinden kaçırmakla görevlendirilir.',
    actors: 'Pedro Pascal\nBella Ramsey\nAnna Torv',
    imdbRating: '8.8/10',
    rating: 9,
    watchedDate: '2024-01-20',
    companions: ['Eşim'],
    notes: 'Oyunun ruhunu çok iyi yakalamış.',
    seasons: 1,
    totalEpisodes: 9,
    trailerLink: 'https://www.youtube.com/watch?v=uLtkt8BonwM'
  },
  {
    id: 's12',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Dark',
    turkishTitle: 'Dark',
    releaseYear: '2017',
    category: 'Bilim Kurgu',
    plot: 'Bir çocuğun kaybolmasıyla başlayan olaylar, dört ailenin üç nesil boyunca süregelen gizemli bağlarını ortaya çıkarır.',
    actors: 'Louis Hofmann\nKaroline Eichhorn\nLisa Vicari',
    imdbRating: '8.7/10',
    rating: 10,
    watchedDate: '2024-02-15',
    companions: ['Eşim'],
    notes: 'Beyin yakan bir kurgu.',
    seasons: 3,
    totalEpisodes: 26,
    trailerLink: 'https://www.youtube.com/watch?v=rrwycJ08PSA'
  },
  {
    id: 's13',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Money Heist',
    turkishTitle: 'La Casa de Papel',
    releaseYear: '2017',
    category: 'Aksiyon',
    plot: 'Profesör lakaplı bir deha, İspanya Kraliyet Darphanesi\'ni soymak için sekiz suçludan oluşan bir ekip kurar.',
    actors: 'Úrsula Corberó\nÁlvaro Morte\nItziar Ituño',
    imdbRating: '8.2/10',
    rating: 8,
    watchedDate: '2024-03-01',
    companions: ['Arkadaşlarım'],
    notes: 'Heyecan dolu bir dizi.',
    seasons: 5,
    totalEpisodes: 41,
    trailerLink: 'https://www.youtube.com/watch?v=hMANIarjT50'
  },
  {
    id: 's14',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Squid Game',
    turkishTitle: 'Squid Game',
    releaseYear: '2021',
    category: 'Dram',
    plot: 'Borç batağındaki yüzlerce kişi, büyük bir para ödülü için ölümcül çocuk oyunlarında yarışmayı kabul eder.',
    actors: 'Lee Jung-jae\nPark Hae-soo\nJung Ho-yeon',
    imdbRating: '8.0/10',
    rating: 8,
    watchedDate: '2024-03-20',
    companions: ['Eşim'],
    notes: 'Sosyal eleştirisi güçlü.',
    seasons: 1,
    totalEpisodes: 9,
    trailerLink: 'https://www.youtube.com/watch?v=oqxAJKy0ii4'
  },
  {
    id: 's15',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Better Call Saul',
    turkishTitle: 'Better Call Saul',
    releaseYear: '2015',
    category: 'Dram',
    plot: 'Breaking Bad\'in öncesini anlatan dizi, avukat Jimmy McGill\'in Saul Goodman\'a dönüşüm sürecini konu alır.',
    actors: 'Bob Odenkirk\nRhea Seehorn\nJonathan Banks',
    imdbRating: '9.0/10',
    rating: 10,
    watchedDate: '2024-04-10',
    companions: ['Yalnız'],
    notes: 'Breaking Bad kadar iyi, hatta bazı yönlerden daha iyi.',
    seasons: 6,
    totalEpisodes: 63,
    trailerLink: 'https://www.youtube.com/watch?v=HN4oydykJFc'
  },
  {
    id: 's16',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Chernobyl',
    turkishTitle: 'Chernobyl',
    releaseYear: '2019',
    category: 'Dram',
    plot: '1986 yılında Sovyetler Birliği\'nde meydana gelen nükleer felaketin ve sonrasındaki kurtarma çalışmalarının gerçek hikayesi.',
    actors: 'Jared Harris\nStellan Skarsgård\nEmily Watson',
    imdbRating: '9.4/10',
    rating: 10,
    watchedDate: '2024-05-01',
    companions: ['Eşim'],
    notes: 'Çok etkileyici ve sarsıcı.',
    seasons: 1,
    totalEpisodes: 5,
    trailerLink: 'https://www.youtube.com/watch?v=s9APLXM9Ei8'
  },
  {
    id: 's17',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'The Mandalorian',
    turkishTitle: 'The Mandalorian',
    releaseYear: '2019',
    category: 'Bilim Kurgu',
    plot: 'İmparatorluğun çöküşünden sonra, galaksinin uzak köşelerinde yalnız bir ödül avcısının maceraları.',
    actors: 'Pedro Pascal\nCarl Weathers\nGiancarlo Esposito',
    imdbRating: '8.7/10',
    rating: 9,
    watchedDate: '2024-05-20',
    companions: ['Ailem'],
    notes: 'Star Wars evrenine taze bir soluk.',
    seasons: 3,
    totalEpisodes: 24,
    trailerLink: 'https://www.youtube.com/watch?v=aOC8E8z_ifw'
  },
  {
    id: 's18',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Peaky Blinders',
    turkishTitle: 'Peaky Blinders',
    releaseYear: '2013',
    category: 'Dram',
    plot: 'Birinci Dünya Savaşı sonrası Birmingham\'da, Shelby ailesinin liderliğindeki bir suç çetesinin yükselişi.',
    actors: 'Cillian Murphy\nPaul Anderson\nHelen McCrory',
    imdbRating: '8.8/10',
    rating: 9,
    watchedDate: '2024-06-15',
    companions: ['Arkadaşlarım'],
    notes: 'Thomas Shelby karakteri çok karizmatik.',
    seasons: 6,
    totalEpisodes: 36,
    trailerLink: 'https://www.youtube.com/watch?v=oVzVdvGIC7U'
  },
  {
    id: 's19',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Watched',
    originalTitle: 'Arcane',
    turkishTitle: 'Arcane',
    releaseYear: '2021',
    category: 'Animasyon',
    plot: 'League of Legends evreninde geçen dizi, iki kız kardeşin zıt taraflarda yer aldığı bir savaşı konu alır.',
    actors: 'Hailee Steinfeld\nElla Purnell\nKevin Alejandro',
    imdbRating: '9.0/10',
    rating: 10,
    watchedDate: '2024-07-10',
    companions: ['Arkadaşlarım'],
    notes: 'Animasyon kalitesi inanılmaz.',
    seasons: 1,
    totalEpisodes: 9,
    trailerLink: 'https://www.youtube.com/watch?v=fXmAurh012s'
  },
  {
    id: 's20',
    createdAt: new Date().toISOString(),
    type: 'Series',
    status: 'Upcoming',
    originalTitle: 'The Bear Season 3',
    turkishTitle: 'The Bear 3. Sezon',
    releaseYear: '2024',
    category: 'Dram',
    plot: 'Carmy ve ekibi, dükkanlarını yeni bir seviyeye taşımaya çalışırken karşılaştıkları zorluklar.',
    actors: 'Jeremy Allen White\nAyo Edebiri\nEbon Moss-Bachrach',
    imdbRating: '8.6/10',
    rating: 0,
    releaseDate: '2024-06-27',
    companions: [],
    notes: 'Heyecanla bekliyorum.',
    seasons: 3,
    totalEpisodes: 10,
    trailerLink: 'https://www.youtube.com/watch?v=i5Uv6CBq_3w'
  }
];
